export const siteConfig = {
  title: "HansBug 的个人技术博客",
  shortTitle: "HansBug 技术博客",
  description:
    "HansBug 的中文个人技术博客新站。这里会逐步整理新写作、项目记录与知识索引，并保留旧博客园入口。",
  tagline: "把旧积累收束起来，再慢慢写出新的东西。",
  author: "HansBug",
  email: "hansbug@buaa.edu.cn",
  siteUrl: "https://hansbug.github.io",
  repoUrl: "https://github.com/HansBug/HansBug.github.io",
  repoName: "HansBug/HansBug.github.io",
  avatarPath: "/avatar.png",
  oldBlogArchivePath: "/old-blog/",
  oldBlogUrl: "https://www.cnblogs.com/HansBug/",
  issueUrl: "https://github.com/HansBug/HansBug.github.io/issues/new/choose",
  discussionsUrl: "https://github.com/HansBug/HansBug.github.io/discussions",
  rssUrl: "/rss.xml",
  nav: [
    { label: "首页", href: "/" },
    { label: "博客", href: "/blog/" },
    { label: "标签", href: "/tags/" },
    { label: "归档", href: "/archive/" },
    { label: "路线", href: "/routes/" },
    { label: "项目", href: "/projects/" },
    { label: "关于", href: "/about/" },
    { label: "联系", href: "/contact/" },
    { label: "搜索", href: "/search/" },
    { label: "旧站归档", href: "/old-blog/" },
  ],
  socialLinks: [
    { label: "GitHub", href: "https://github.com/HansBug" },
    { label: "博客园", href: "https://www.cnblogs.com/HansBug/" },
    { label: "邮箱", href: "mailto:hansbug@buaa.edu.cn" },
    { label: "RSS", href: "/rss.xml" },
  ],
} as const;
