export const siteConfig = {
  title: "HansBug 的个人技术博客",
  shortTitle: "HansBug 技术博客",
  description:
    "HansBug 的中文个人技术博客新站。这里会逐步整理新写作、项目记录与知识索引，并保留旧博客园入口。",
  tagline: "新文章、标签与归档，会慢慢整理到这里。",
  author: "HansBug",
  email: "hansbug@buaa.edu.cn",
  siteUrl: "https://hansbug.github.io",
  repoUrl: "https://github.com/HansBug/HansBug.github.io",
  repoName: "HansBug/HansBug.github.io",
  avatarPath: "/avatar.png",
  oldBlogArchivePath: "/old-blog/",
  oldBlogUrl: "https://www.cnblogs.com/HansBug/",
  issueUrl: "https://github.com/HansBug/HansBug.github.io/issues/new/choose",
  discussionsUrl: "https://github.com/HansBug/HansBug.github.io/discussions",
  rssUrl: "/rss.xml",
  nav: [
    { label: "首页", href: "/", icon: "home" },
    { label: "博客", href: "/blog/", icon: "blog" },
    { label: "标签", href: "/tags/", icon: "tag" },
    { label: "归档", href: "/archive/", icon: "archive" },
    { label: "联系", href: "/contact/", icon: "mail" },
    { label: "旧站归档", href: "/old-blog/", icon: "history" },
  ],
  socialLinks: [
    { label: "GitHub", href: "https://github.com/HansBug" },
    { label: "博客园", href: "https://www.cnblogs.com/HansBug/" },
    { label: "邮箱", href: "mailto:hansbug@buaa.edu.cn" },
    { label: "RSS", href: "/rss.xml" },
  ],
} as const;
